version: '3.8'

services:
  api:
    container_name: project-management_p
    image: project-management_p:v1
    build: .
    ports:
      - '3007:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db_p
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=Abcd1234!
      - DB_DATABASE=p_collaboration
      - JWT_SECRET=238bb80d-a201-49ca-97c8-bf3e1cb84fca
      - JWT_EXPIRATION=1d
    depends_on:
      - db_p
    networks:
      - user_network_p
    volumes:
      - ./config:/app/config
    command: yarn start:dev

  db_p:
    image: postgres:14.1-alpine
    container_name: postgres_db_p
    restart: always
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Abcd1234!
      - POSTGRES_DB=p_collaboration
    volumes:
      - db_p:/var/lib/postgresql/data
    networks:
      - user_network_p

volumes:
  db_p:
networks:
  user_network_p:
    name: user_network_p
    driver: bridge
