version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_DATABASE=p_collaboration
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    command: yarn start:dev

  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=p_collaboration
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
